spring.application.name=walletsync
# ===============================
# CONFIGURACI?N DE DATASOURCE
# ===============================
# Cambia 'localhost:5432' por tu host y 'database_name' por el nombre de tu base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/walletsync_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACI?N DE JPA / HIBERNATE
# ===============================
# 'update' crea o actualiza las tablas autom?ticamente.
# Usa 'validate' o 'none' en entornos de producci?n.
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola (?til para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Especifica el dialecto de PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect